// <auto-generated />
namespace WAD_T2104E_NHAT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class productMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202209131326450_productMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
